== Estados de Sinais Especiais

Em verilog, além dos valores binários tradicionais (0 e 1), existem outros estados de sinais que podem ser utilizados para representar condições especiais. Esses estados são especialmente úteis em simulações e na modelagem de circuitos digitais complexos. A seguir, estão os principais estados de sinais especiais:

* x (indeterminado)
* z (alta impedância)
* ? (dont'care)

== x (Indeterminado)
O estado `x` é utilizado para representar um valor indeterminado ou desconhecido. Isso pode ocorrer quando um sinal não foi inicializado ou quando há uma condição de conflito entre dois sinais que tentam assumir valores diferentes. Em simulações, o estado `x` é frequentemente usado para indicar que o valor de um sinal não pode ser determinado.
[source,verilog]
----
module exemplo(
    input entrada,
    output saida
)
    if (entrada == 1'b1) begin
        saida = 1'b0;
    end
endmodule
----

No exemplo acima, se a entrada for 1, a saída será 0. No entanto, se a entrada não for 1 (por exemplo, se for 0 ou não estiver definida), a saída permanecerá em um estado indeterminado (`x`). se tentar utilizare uma saída em estado indeterminado em um circuito real, ela poderá causar comportamentos inesperados, pois o circuito não saberá como interpretar esse valor.
[source,verilog]
----
reg a;
initial begin
    a = 1'bx; // a é inicializado como indeterminado
end
----

== z (Alta Impedância)
O estado `z` é utilizado para representar alta impedância, que é um estado que indica que um fio está desconectado, não está dirigindo nem 0 nem 1.
[source,verilog]
----
module exemplo(
    input entrada,
    output saida
)
    if (entrada == 1'b1) begin
        saida = 1'bz; // se entrada for 1, saida será alta impedância
    end else begin
        saida = 1'b0; // se entrada for 0, saida será 0
    end
----
No exemplo acima, se a entrada for 1, a saída será alta impedância (`z`), indicando que o fio não está dirigindo nenhum valor. Se a entrada for 0, a saída será 0. Se tentar utilizar uma saída em alta impedância em um circuito real, ela não irá afetar o estado do circuito conectado a ela, pois não está dirigindo nenhum valor.

== ? (Dont'Care)
O estado `?` é utilizado para indicar que o valor de um sinal não é relevante em uma determinada condição. Isso é útil em simulações e testes, onde você pode querer ignorar o valor de um sinal em certas situações.
[source,verilog]
----
casez (entrada)
    4'b10??: saida = 1; // os dois bits menos significativos podem ser 0 ou 1
    default: saida = 0;
endcase
----
No caso acima, o `casez` permite que os dois bits menos significativos da entrada sejam ignorados (podem ser 0 ou 1), enquanto os outros bits devem corresponder exatamente ao valor especificado.